market_data:
  symbols: ['AAPL', 'MSFT', 'GOOGL']
  buffer_size: 10000
  max_depth: 10

storage:
  base_path: "data"
  compression: "snappy"
  partition_cols: ["symbol", "date"]

log_config_path: "config/logging_config.yaml"