version: 1
disable_existing_loggers: false

formatters:
    standard:
        format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
    detailed:
        format: '%(asctime)s [%(levelname)s] %(name)s:%(lineno)d: %(message)s'

handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: standard
        stream: ext://sys.stdout

    file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: detailed
        filename: logs/market_data_pipeline.log
        maxBytes: 10485760  # 10MB
        backupCount: 5
        encoding: utf8

loggers:
    market_data_pipeline:
        level: DEBUG
        handlers: [console, file]
        propagate: false

root:
    level: INFO
    handlers: [console]